checks:
    php: true
    javascript: true

filter:
    paths:
        - 'media-credit.php'
        - 'uninstall.php'
        - 'includes/'
        - 'admin/'
        - 'public/'
    dependency_paths:
        - wordpress/

build:
    cache:
        directories:
            - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
            # vendor is already included.
    environment:
        rabbitmq: false
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        php:
            version: 7.2
    nodes:
        analysis:
            project_setup:
                override: true
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress-core
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - js-scrutinizer-run --enable-security-analysis
                    - eslint-run
                    - phpcs-run --standard=phpcs.xml media-credit.php uninstall.php admin/ public/ includes/ --extensions=php

tools:
    php_code_sniffer: false
    php_cs_fixer: false
    external_code_coverage: false
